apiVersion: v2
name: shukra-operator
version: 0.3.0
appVersion: 0.3.0
description: Shukra Operator — One YAML. Complete Environment.
icon: https://raw.githubusercontent.com/sandy001-kki/Shukra/main/docs/assets/shukla.png
