// Code generated by hand for this repository until protoc is wired into the
// build. Source of truth: bridge.proto.
package bridgev1

import (
	proto "github.com/golang/protobuf/proto"
	encoding "google.golang.org/grpc/encoding"
)

func init() {
	encoding.RegisterCodec(legacyProtoCodec{})
}

type legacyProtoCodec struct{}

func (legacyProtoCodec) Marshal(v interface{}) ([]byte, error) {
	return proto.Marshal(v.(proto.Message))
}

func (legacyProtoCodec) Unmarshal(data []byte, v interface{}) error {
	return proto.Unmarshal(data, v.(proto.Message))
}

func (legacyProtoCodec) Name() string {
	return "proto"
}

type HealthStreamRequest struct {
	Namespace       string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name            string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IntervalSeconds int32  `protobuf:"varint,3,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
}

type HealthEvent struct {
	Name            string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace       string                  `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Phase           string                  `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	ReadyReplicas   int32                   `protobuf:"varint,4,opt,name=ready_replicas,json=readyReplicas,proto3" json:"ready_replicas,omitempty"`
	DesiredReplicas int32                   `protobuf:"varint,5,opt,name=desired_replicas,json=desiredReplicas,proto3" json:"desired_replicas,omitempty"`
	FailureCount    int32                   `protobuf:"varint,6,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	LastError       string                  `protobuf:"bytes,7,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	Conditions      []*ConditionProto       `protobuf:"bytes,8,rep,name=conditions,proto3" json:"conditions,omitempty"`
	IntentHealth    []*IntentConditionProto `protobuf:"bytes,9,rep,name=intent_health,json=intentHealth,proto3" json:"intent_health,omitempty"`
	TimestampUnix   int64                   `protobuf:"varint,10,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
}

type ReconcileEventRequest struct {
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

type ReconcileEvent struct {
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	EventType     string `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	ResourceKind  string `protobuf:"bytes,4,opt,name=resource_kind,json=resourceKind,proto3" json:"resource_kind,omitempty"`
	Message       string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	Error         string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	DurationMs    int64  `protobuf:"varint,7,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	TimestampUnix int64  `protobuf:"varint,8,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
}

type PatchRequest struct {
	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PatchJson string `protobuf:"bytes,3,opt,name=patch_json,json=patchJson,proto3" json:"patch_json,omitempty"`
	PatchId   string `protobuf:"bytes,4,opt,name=patch_id,json=patchId,proto3" json:"patch_id,omitempty"`
	Reason    string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	AppliedBy string `protobuf:"bytes,6,opt,name=applied_by,json=appliedBy,proto3" json:"applied_by,omitempty"`
}

type PatchResult struct {
	Success         bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error           string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	ResourceVersion string `protobuf:"bytes,3,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
}

type ShadowCreateRequest struct {
	SourceName      string `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	SourceNamespace string `protobuf:"bytes,2,opt,name=source_namespace,json=sourceNamespace,proto3" json:"source_namespace,omitempty"`
	PatchId         string `protobuf:"bytes,3,opt,name=patch_id,json=patchId,proto3" json:"patch_id,omitempty"`
	ImageOverride   string `protobuf:"bytes,4,opt,name=image_override,json=imageOverride,proto3" json:"image_override,omitempty"`
	SpecPatchJson   string `protobuf:"bytes,5,opt,name=spec_patch_json,json=specPatchJson,proto3" json:"spec_patch_json,omitempty"`
	TtlSeconds      int32  `protobuf:"varint,6,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
}

type ShadowResult struct {
	Success         bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ShadowName      string `protobuf:"bytes,2,opt,name=shadow_name,json=shadowName,proto3" json:"shadow_name,omitempty"`
	ShadowNamespace string `protobuf:"bytes,3,opt,name=shadow_namespace,json=shadowNamespace,proto3" json:"shadow_namespace,omitempty"`
	Error           string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

type ShadowDeleteRequest struct {
	ShadowName      string `protobuf:"bytes,1,opt,name=shadow_name,json=shadowName,proto3" json:"shadow_name,omitempty"`
	ShadowNamespace string `protobuf:"bytes,2,opt,name=shadow_namespace,json=shadowNamespace,proto3" json:"shadow_namespace,omitempty"`
}

type DeleteResult struct {
	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

type IntentViolationRequest struct {
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

type IntentViolationEvent struct {
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	IntentType    string `protobuf:"bytes,3,opt,name=intent_type,json=intentType,proto3" json:"intent_type,omitempty"`
	Declared      string `protobuf:"bytes,4,opt,name=declared,proto3" json:"declared,omitempty"`
	Measured      string `protobuf:"bytes,5,opt,name=measured,proto3" json:"measured,omitempty"`
	Severity      string `protobuf:"bytes,6,opt,name=severity,proto3" json:"severity,omitempty"`
	TimestampUnix int64  `protobuf:"varint,7,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
}

type ListRequest struct {
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

type EnvironmentList struct {
	Environments []*EnvironmentSummary `protobuf:"bytes,1,rep,name=environments,proto3" json:"environments,omitempty"`
}

type EnvironmentSummary struct {
	Name                        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace                   string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Phase                       string `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	FailureCount                int32  `protobuf:"varint,4,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	LastError                   string `protobuf:"bytes,5,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	LastSuccessfulReconcileUnix int64  `protobuf:"varint,6,opt,name=last_successful_reconcile_unix,json=lastSuccessfulReconcileUnix,proto3" json:"last_successful_reconcile_unix,omitempty"`
}

type GetRequest struct {
	Name      string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

type EnvironmentDetail struct {
	Name           string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace      string                  `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Phase          string                  `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	SpecJson       string                  `protobuf:"bytes,4,opt,name=spec_json,json=specJson,proto3" json:"spec_json,omitempty"`
	StatusJson     string                  `protobuf:"bytes,5,opt,name=status_json,json=statusJson,proto3" json:"status_json,omitempty"`
	Conditions     []*ConditionProto       `protobuf:"bytes,6,rep,name=conditions,proto3" json:"conditions,omitempty"`
	IntentHealth   []*IntentConditionProto `protobuf:"bytes,7,rep,name=intent_health,json=intentHealth,proto3" json:"intent_health,omitempty"`
	ChildResources []string                `protobuf:"bytes,8,rep,name=child_resources,json=childResources,proto3" json:"child_resources,omitempty"`
}

type ConditionProto struct {
	Type               string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Status             string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Reason             string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message            string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	LastTransitionUnix int64  `protobuf:"varint,5,opt,name=last_transition_unix,json=lastTransitionUnix,proto3" json:"last_transition_unix,omitempty"`
}

type IntentConditionProto struct {
	Type          string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Status        string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Measured      string `protobuf:"bytes,3,opt,name=measured,proto3" json:"measured,omitempty"`
	Declared      string `protobuf:"bytes,4,opt,name=declared,proto3" json:"declared,omitempty"`
	Message       string `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	LastCheckUnix int64  `protobuf:"varint,6,opt,name=last_check_unix,json=lastCheckUnix,proto3" json:"last_check_unix,omitempty"`
}

func (*HealthStreamRequest) Reset()              {}
func (*HealthStreamRequest) ProtoMessage()       {}
func (m *HealthStreamRequest) String() string    { return proto.CompactTextString(m) }
func (*HealthEvent) Reset()                      {}
func (*HealthEvent) ProtoMessage()               {}
func (m *HealthEvent) String() string            { return proto.CompactTextString(m) }
func (*ReconcileEventRequest) Reset()            {}
func (*ReconcileEventRequest) ProtoMessage()     {}
func (m *ReconcileEventRequest) String() string  { return proto.CompactTextString(m) }
func (*ReconcileEvent) Reset()                   {}
func (*ReconcileEvent) ProtoMessage()            {}
func (m *ReconcileEvent) String() string         { return proto.CompactTextString(m) }
func (*PatchRequest) Reset()                     {}
func (*PatchRequest) ProtoMessage()              {}
func (m *PatchRequest) String() string           { return proto.CompactTextString(m) }
func (*PatchResult) Reset()                      {}
func (*PatchResult) ProtoMessage()               {}
func (m *PatchResult) String() string            { return proto.CompactTextString(m) }
func (*ShadowCreateRequest) Reset()              {}
func (*ShadowCreateRequest) ProtoMessage()       {}
func (m *ShadowCreateRequest) String() string    { return proto.CompactTextString(m) }
func (*ShadowResult) Reset()                     {}
func (*ShadowResult) ProtoMessage()              {}
func (m *ShadowResult) String() string           { return proto.CompactTextString(m) }
func (*ShadowDeleteRequest) Reset()              {}
func (*ShadowDeleteRequest) ProtoMessage()       {}
func (m *ShadowDeleteRequest) String() string    { return proto.CompactTextString(m) }
func (*DeleteResult) Reset()                     {}
func (*DeleteResult) ProtoMessage()              {}
func (m *DeleteResult) String() string           { return proto.CompactTextString(m) }
func (*IntentViolationRequest) Reset()           {}
func (*IntentViolationRequest) ProtoMessage()    {}
func (m *IntentViolationRequest) String() string { return proto.CompactTextString(m) }
func (*IntentViolationEvent) Reset()             {}
func (*IntentViolationEvent) ProtoMessage()      {}
func (m *IntentViolationEvent) String() string   { return proto.CompactTextString(m) }
func (*ListRequest) Reset()                      {}
func (*ListRequest) ProtoMessage()               {}
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*EnvironmentList) Reset()                  {}
func (*EnvironmentList) ProtoMessage()           {}
func (m *EnvironmentList) String() string        { return proto.CompactTextString(m) }
func (*EnvironmentSummary) Reset()               {}
func (*EnvironmentSummary) ProtoMessage()        {}
func (m *EnvironmentSummary) String() string     { return proto.CompactTextString(m) }
func (*GetRequest) Reset()                       {}
func (*GetRequest) ProtoMessage()                {}
func (m *GetRequest) String() string             { return proto.CompactTextString(m) }
func (*EnvironmentDetail) Reset()                {}
func (*EnvironmentDetail) ProtoMessage()         {}
func (m *EnvironmentDetail) String() string      { return proto.CompactTextString(m) }
func (*ConditionProto) Reset()                   {}
func (*ConditionProto) ProtoMessage()            {}
func (m *ConditionProto) String() string         { return proto.CompactTextString(m) }
func (*IntentConditionProto) Reset()             {}
func (*IntentConditionProto) ProtoMessage()      {}
func (m *IntentConditionProto) String() string   { return proto.CompactTextString(m) }
