// Code generated by hand for this repository until protoc is wired into the
// build. Source of truth: bridge.proto.
package bridgev1

import (
	context "context"

	grpc "google.golang.org/grpc"
)

type AionosBridgeClient interface {
	StreamEnvironmentHealth(ctx context.Context, in *HealthStreamRequest, opts ...grpc.CallOption) (AionosBridge_StreamEnvironmentHealthClient, error)
	StreamReconcileEvents(ctx context.Context, in *ReconcileEventRequest, opts ...grpc.CallOption) (AionosBridge_StreamReconcileEventsClient, error)
	PatchEnvironment(ctx context.Context, in *PatchRequest, opts ...grpc.CallOption) (*PatchResult, error)
	CreateShadowEnvironment(ctx context.Context, in *ShadowCreateRequest, opts ...grpc.CallOption) (*ShadowResult, error)
	DeleteShadowEnvironment(ctx context.Context, in *ShadowDeleteRequest, opts ...grpc.CallOption) (*DeleteResult, error)
	StreamIntentViolations(ctx context.Context, in *IntentViolationRequest, opts ...grpc.CallOption) (AionosBridge_StreamIntentViolationsClient, error)
	ListEnvironments(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*EnvironmentList, error)
	GetEnvironment(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*EnvironmentDetail, error)
}

type aionosBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewAionosBridgeClient(cc grpc.ClientConnInterface) AionosBridgeClient {
	return &aionosBridgeClient{cc}
}

func (c *aionosBridgeClient) StreamEnvironmentHealth(ctx context.Context, in *HealthStreamRequest, opts ...grpc.CallOption) (AionosBridge_StreamEnvironmentHealthClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AionosBridge_serviceDesc.Streams[0], "/aionos.bridge.v1.AionosBridge/StreamEnvironmentHealth", opts...)
	if err != nil {
		return nil, err
	}
	x := &aionosBridgeStreamEnvironmentHealthClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AionosBridge_StreamEnvironmentHealthClient interface {
	Recv() (*HealthEvent, error)
	grpc.ClientStream
}

type aionosBridgeStreamEnvironmentHealthClient struct {
	grpc.ClientStream
}

func (x *aionosBridgeStreamEnvironmentHealthClient) Recv() (*HealthEvent, error) {
	m := new(HealthEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aionosBridgeClient) StreamReconcileEvents(ctx context.Context, in *ReconcileEventRequest, opts ...grpc.CallOption) (AionosBridge_StreamReconcileEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AionosBridge_serviceDesc.Streams[1], "/aionos.bridge.v1.AionosBridge/StreamReconcileEvents", opts...)
	if err != nil {
		return nil, err
	}
	x := &aionosBridgeStreamReconcileEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AionosBridge_StreamReconcileEventsClient interface {
	Recv() (*ReconcileEvent, error)
	grpc.ClientStream
}

type aionosBridgeStreamReconcileEventsClient struct {
	grpc.ClientStream
}

func (x *aionosBridgeStreamReconcileEventsClient) Recv() (*ReconcileEvent, error) {
	m := new(ReconcileEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aionosBridgeClient) PatchEnvironment(ctx context.Context, in *PatchRequest, opts ...grpc.CallOption) (*PatchResult, error) {
	out := new(PatchResult)
	err := c.cc.Invoke(ctx, "/aionos.bridge.v1.AionosBridge/PatchEnvironment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aionosBridgeClient) CreateShadowEnvironment(ctx context.Context, in *ShadowCreateRequest, opts ...grpc.CallOption) (*ShadowResult, error) {
	out := new(ShadowResult)
	err := c.cc.Invoke(ctx, "/aionos.bridge.v1.AionosBridge/CreateShadowEnvironment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aionosBridgeClient) DeleteShadowEnvironment(ctx context.Context, in *ShadowDeleteRequest, opts ...grpc.CallOption) (*DeleteResult, error) {
	out := new(DeleteResult)
	err := c.cc.Invoke(ctx, "/aionos.bridge.v1.AionosBridge/DeleteShadowEnvironment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aionosBridgeClient) StreamIntentViolations(ctx context.Context, in *IntentViolationRequest, opts ...grpc.CallOption) (AionosBridge_StreamIntentViolationsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AionosBridge_serviceDesc.Streams[2], "/aionos.bridge.v1.AionosBridge/StreamIntentViolations", opts...)
	if err != nil {
		return nil, err
	}
	x := &aionosBridgeStreamIntentViolationsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AionosBridge_StreamIntentViolationsClient interface {
	Recv() (*IntentViolationEvent, error)
	grpc.ClientStream
}

type aionosBridgeStreamIntentViolationsClient struct {
	grpc.ClientStream
}

func (x *aionosBridgeStreamIntentViolationsClient) Recv() (*IntentViolationEvent, error) {
	m := new(IntentViolationEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aionosBridgeClient) ListEnvironments(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*EnvironmentList, error) {
	out := new(EnvironmentList)
	err := c.cc.Invoke(ctx, "/aionos.bridge.v1.AionosBridge/ListEnvironments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aionosBridgeClient) GetEnvironment(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*EnvironmentDetail, error) {
	out := new(EnvironmentDetail)
	err := c.cc.Invoke(ctx, "/aionos.bridge.v1.AionosBridge/GetEnvironment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type AionosBridgeServer interface {
	StreamEnvironmentHealth(*HealthStreamRequest, AionosBridge_StreamEnvironmentHealthServer) error
	StreamReconcileEvents(*ReconcileEventRequest, AionosBridge_StreamReconcileEventsServer) error
	PatchEnvironment(context.Context, *PatchRequest) (*PatchResult, error)
	CreateShadowEnvironment(context.Context, *ShadowCreateRequest) (*ShadowResult, error)
	DeleteShadowEnvironment(context.Context, *ShadowDeleteRequest) (*DeleteResult, error)
	StreamIntentViolations(*IntentViolationRequest, AionosBridge_StreamIntentViolationsServer) error
	ListEnvironments(context.Context, *ListRequest) (*EnvironmentList, error)
	GetEnvironment(context.Context, *GetRequest) (*EnvironmentDetail, error)
}

type AionosBridge_StreamEnvironmentHealthServer interface {
	Send(*HealthEvent) error
	grpc.ServerStream
}

type AionosBridge_StreamReconcileEventsServer interface {
	Send(*ReconcileEvent) error
	grpc.ServerStream
}

type AionosBridge_StreamIntentViolationsServer interface {
	Send(*IntentViolationEvent) error
	grpc.ServerStream
}

func RegisterAionosBridgeServer(s *grpc.Server, srv AionosBridgeServer) {
	s.RegisterService(&_AionosBridge_serviceDesc, srv)
}

func _AionosBridge_StreamEnvironmentHealth_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HealthStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AionosBridgeServer).StreamEnvironmentHealth(m, &aionosBridgeStreamEnvironmentHealthServer{stream})
}

type aionosBridgeStreamEnvironmentHealthServer struct{ grpc.ServerStream }

func (x *aionosBridgeStreamEnvironmentHealthServer) Send(m *HealthEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _AionosBridge_StreamReconcileEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReconcileEventRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AionosBridgeServer).StreamReconcileEvents(m, &aionosBridgeStreamReconcileEventsServer{stream})
}

type aionosBridgeStreamReconcileEventsServer struct{ grpc.ServerStream }

func (x *aionosBridgeStreamReconcileEventsServer) Send(m *ReconcileEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _AionosBridge_PatchEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AionosBridgeServer).PatchEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/aionos.bridge.v1.AionosBridge/PatchEnvironment"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AionosBridgeServer).PatchEnvironment(ctx, req.(*PatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AionosBridge_CreateShadowEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShadowCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AionosBridgeServer).CreateShadowEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/aionos.bridge.v1.AionosBridge/CreateShadowEnvironment"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AionosBridgeServer).CreateShadowEnvironment(ctx, req.(*ShadowCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AionosBridge_DeleteShadowEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShadowDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AionosBridgeServer).DeleteShadowEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/aionos.bridge.v1.AionosBridge/DeleteShadowEnvironment"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AionosBridgeServer).DeleteShadowEnvironment(ctx, req.(*ShadowDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AionosBridge_StreamIntentViolations_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(IntentViolationRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AionosBridgeServer).StreamIntentViolations(m, &aionosBridgeStreamIntentViolationsServer{stream})
}

type aionosBridgeStreamIntentViolationsServer struct{ grpc.ServerStream }

func (x *aionosBridgeStreamIntentViolationsServer) Send(m *IntentViolationEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _AionosBridge_ListEnvironments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AionosBridgeServer).ListEnvironments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/aionos.bridge.v1.AionosBridge/ListEnvironments"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AionosBridgeServer).ListEnvironments(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AionosBridge_GetEnvironment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AionosBridgeServer).GetEnvironment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: "/aionos.bridge.v1.AionosBridge/GetEnvironment"}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AionosBridgeServer).GetEnvironment(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AionosBridge_serviceDesc = grpc.ServiceDesc{
	ServiceName: "aionos.bridge.v1.AionosBridge",
	HandlerType: (*AionosBridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "PatchEnvironment", Handler: _AionosBridge_PatchEnvironment_Handler},
		{MethodName: "CreateShadowEnvironment", Handler: _AionosBridge_CreateShadowEnvironment_Handler},
		{MethodName: "DeleteShadowEnvironment", Handler: _AionosBridge_DeleteShadowEnvironment_Handler},
		{MethodName: "ListEnvironments", Handler: _AionosBridge_ListEnvironments_Handler},
		{MethodName: "GetEnvironment", Handler: _AionosBridge_GetEnvironment_Handler},
	},
	Streams: []grpc.StreamDesc{
		{StreamName: "StreamEnvironmentHealth", Handler: _AionosBridge_StreamEnvironmentHealth_Handler, ServerStreams: true},
		{StreamName: "StreamReconcileEvents", Handler: _AionosBridge_StreamReconcileEvents_Handler, ServerStreams: true},
		{StreamName: "StreamIntentViolations", Handler: _AionosBridge_StreamIntentViolations_Handler, ServerStreams: true},
	},
	Metadata: "api/bridge/v1/bridge.proto",
}
