apiVersion: apps.shukra.io/v1beta1
kind: AppEnvironment
metadata:
  name: autoscaling-app
spec:
  app:
    image: ghcr.io/sandy001-kki/sample:1.0.0
    resources:
      requests: {cpu: 200m, memory: 256Mi}
      limits: {cpu: 1000m, memory: 512Mi}
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 75
