apiVersion: apps.shukra.io/v1beta1
kind: AppEnvironment
metadata:
  name: autoscaling-app
spec:
  app:
    image: nginx:1.27
    containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 10
    readinessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
    resources:
      requests: {cpu: 200m, memory: 256Mi}
      limits: {cpu: 1000m, memory: 512Mi}
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 75
